---
title: "260622_ANCESTOR_Corsym"
author: "GK"
date: "2026-06-22"
output: html_document
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
library(cowplot)
library(patchwork)
library(ggplot2)
library(data.table)
library(purrr)
library(tidyr)
library(knitr)
library(kableExtra)
library(dplyr)
```

```{r functions}
theme_professional <- function(
  base_size = 12,
  base_family = "sans"
) {

  theme_bw(base_size = base_size, base_family = base_family) +
    theme(
      # Text
      text = element_text(color = "black"),
      plot.title = element_text(
        face = "bold",
        size = rel(1.3),
        hjust = 0.5
      ),
      plot.subtitle = element_text(
        size = rel(1.0),
        hjust = 0.5
      ),
      axis.title = element_text(
        face = "bold",
        size = rel(1.1)
      ),
      axis.text = element_text(
        color = "black",
        size = rel(0.9)
      ),

      # Panel
      panel.border = element_rect(
        color = "black",
        linewidth = 0.7
      ),
      panel.grid.major = element_blank(),
      panel.grid.minor = element_blank(),
      panel.background = element_blank(),

      # Axes
      axis.line = element_line(
        color = "black",
        linewidth = 0.5
      ),
      axis.ticks = element_line(
        color = "black",
        linewidth = 0.5
      ),
      axis.ticks.length = unit(0.15, "cm"),

      # Legend
      legend.background = element_blank(),
      legend.key = element_blank(),
      legend.title = element_text(face = "bold"),

      # Facets
      strip.background = element_rect(
        fill = "grey90",
        color = "black"
      ),
      strip.text = element_text(
        face = "bold"
      ),

      # Margins
      plot.margin = margin(10, 10, 10, 10)
    )
}
base_size <- 16
```
```{r functions_2}
quick_point_base <- function(data, x, y,
                       color = NULL,
                       point_size = 3,
                       alpha = 0.7) {

  p <- ggplot(
    data,
    aes(
      x = {{ x }},
      y = {{ y }},
      color = {{ color }}
    )
  ) +
    geom_point(
      size = point_size,
      alpha = alpha
    ) +
    theme_professional(base_size = 30)+
    theme(
      panel.border = element_rect(linewidth = 3),
      legend.position = "bottom"
    )+
        scale_y_continuous(limits = c(0,1))+
        scale_x_continuous(limits = c(0,1))+
  geom_abline(intercept = 0,slope=1,linetype="dashed",size=2)



  return(p)
}

reorder <- function(df, v1, v2, prop = 1) {

  eligible_rows <- which(df[[v1]]>df[[v2]])
  
  n_swap <- round(length(eligible_rows) * prop)

  rows_to_swap <- sample(eligible_rows, n_swap)

  df[[paste0(v1,as.character(prop))]]<-df[[v1]]
  df[[paste0(v2,as.character(prop))]]<-df[[v2]]
  tmp <- df[[v1]][rows_to_swap]
  df[[paste0(v1,as.character(prop))]][rows_to_swap] <- df[[v2]][rows_to_swap]
  df[[paste0(v2,as.character(prop))]][rows_to_swap] <- tmp
  return(df)
}

corsym <- function( Q, q2 = NULL ) {
    # validate inputs
    if ( missing( Q ) )
        stop( '`Q` is required!' )
    if ( is.null( q2 ) ) {
        # in this mode, Q must be a matrix with 2 columns
        if ( !is.matrix( Q ) )
            stop( 'When a single argument `Q` is provided, it must be a matrix!' )
        if ( ncol( Q ) != 2 )
            stop( '`Q` must have 2 columns!' )
        # extract the two vectors of interest
        q1 <- Q[ , 1 ]
        q2 <- Q[ , 2 ]
        n <- nrow( Q )
    } else {
        # in this case both need to be vectors of equal length
        q1 <- Q # rename internally
        # make sure length is equal
        n <- length( q1 )
        if( length( q2 ) != n )
            stop( 'Both inputs must have the same length!' )
    }
    
    # n only appears as 2*n...
    nn <- 2 * n
    
    # estimate pooled mean
    # this uses a bit less memory than concatenating q1 and q2 first
    mu <- ( mean( q1 ) + mean( q2 ) ) / 2
    # now estimate "base" pooled variance
    sigma_sq <- ( sum( ( q1 - mu )^2 ) + sum( ( q2 - mu )^2 ) ) / ( nn - 1 )
    # and "base" covariance estimate
    covar <- sum( ( q1 - mu ) * ( q2 - mu ) ) * 2 / ( nn - 1 )

    # now form small sample unbiased estimates
    an <- ( nn - 1 ) ^2 / ( nn * ( nn - 2 ) )
    bn <- an / ( nn - 1 )
    sigma_sq_u <- an * sigma_sq + bn * covar
    covar_u <- an * covar + bn * sigma_sq

    # finally, estimate correlation and return!
    return( covar_u / sigma_sq_u )
}

```

```{r make dataset}
set.seed(123)

all_Q3 <- read.csv("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/admixture_analysis/TRIOS_HGDP_all_chrs_bfile_ldpruned.3.Q",sep=" ",header=FALSE)
all_fam<-read.csv("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/admixture_analysis/TRIOS_HGDP_all_chrs_bfile_ldpruned.fam",sep="",header=FALSE)
parent_info<-read.csv("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/admixture_analysis/HGDP_with_TGP_trios_merged_ldpruned.fam",sep=" ",header=FALSE)
colnames(parent_info)<-c("coh","id","p1","p2","sex","6")
all<-cbind(all_fam,all_Q3)
colnames(all)<-c("t","id","F1","F2","F3",'F4',"a1","a2","a3")
all <- all %>%
  separate(id,    into = c("coh", "id"),
    sep = "_",    extra = "merge",    fill = "right"  )

all<-all%>%
  dplyr::select(coh,id,a1,a2,a3)
all_Qs<-merge(all,parent_info,by=c("coh","id"),all.x = TRUE)

all<-read.csv("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/hgdp/three_harmonized_rfmix.csv",
               sep=",",header=TRUE)
all <- dcast(
  as.data.table(all),
  individual ~ ancestry,
  value.var = "proportion",
  fill = 0
)
colnames(all)[1]<-"id"

all <- all %>%
  separate(id,    into = c("coh", "id"),
    sep = "_",    extra = "merge",    fill = "right"  )

df<-merge(all_Qs,all,by=c("coh","id"),all = TRUE)


all<-read.csv("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/hgdp/ancestor_3way_HGDP.txt",sep="",header=FALSE)
all<-read.csv("C:/Users/Ictinike/Downloads/ancestor_3way_reorder.txt",sep="",header=FALSE)
#all<-read.csv("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/hgdp/ancestor_3way_redone.txt",sep="",header=FALSE)

colnames(all)<-c("t","P1a","P1b","P1c","P2a","P2b","P2c")
all <- all %>%
  mutate(basename = basename(t)) %>%
  separate(basename,    into = c("coh", "part2"),
    sep = "_",    extra = "merge",    fill = "right"  )%>%
  separate(part2,    into = c("id", "USELESS"),    sep = "_",
    extra = "merge",    fill = "right"  )%>%
  dplyr::select(-c(USELESS,t))
AFR<-read.csv("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/hgdp/ancestor_2way_YRI_v_NonYRI.txt",sep="",header=FALSE)
colnames(AFR)<-c("t","P1a","P1b","P1c","P2a","P2b","P2c")
AFR <- AFR %>%
  mutate(basename = basename(t)) %>%
  separate(basename,    into = c("coh", "part2"),
    sep = "_",    extra = "merge",    fill = "right"  )%>%
  separate(part2,    into = c("id", "USELESS"),    sep = "_",
    extra = "merge",    fill = "right"  )%>%
  dplyr::select(-c(USELESS,t))
df_anc<-merge(all,AFR,by=c("coh","id"),suffixes = (c(".3way",".2way")))
df<-merge(df,df_anc,by=c("coh","id"),all = TRUE)


HGDP<-read.csv("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/hgdp/2way_HGDP_v_IBS.csv",
               sep=",",header=TRUE)
AFR<-read.csv("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/hgdp/2way_YRI_v_nonYRI.csv",
               sep=",",header=TRUE)
HGDP <- dcast(
  as.data.table(HGDP),
  individual ~ ancestry,
  value.var = "proportion",
  fill = 0
)
colnames(HGDP)[1]<-"id"
HGDP <- HGDP %>%
  separate(id,    into = c("coh", "id"),
    sep = "_",    extra = "merge",    fill = "right"  )
AFR <- dcast(
  as.data.table(AFR),
  individual ~ ancestry,
  value.var = "proportion",
  fill = 0
)
colnames(AFR)[1]<-"id"
AFR <- AFR %>%
  separate(id,    into = c("coh", "id"),
    sep = "_",    extra = "merge", fill = "right"  )
twoway_rfmix<-merge(AFR,HGDP,by=c("coh","id"),all.x = TRUE,suffixes = c(".2_AFR",".2_NAT"))

df<-merge(df,twoway_rfmix,by=c("coh","id"),all.x = TRUE)

df$a_NonYRI<-df$a1+df$a2
```

```{r prepare_children_only_and_random_2way}
parent_values_to_grab<-list("sex","a1","a2","a3","a_NonYRI","0","1","2","0.2_AFR","1.2_AFR")
df2<-df
for (pv in parent_values_to_grab){
  df2<-df2%>%
    left_join(df %>% dplyr::select(id, pv),
            by = c("p1" = "id"),
            suffix = c("", ".p1"))
}
for (pv in parent_values_to_grab){
  df2<-df2%>%
    left_join(df %>% dplyr::select(id, pv),
            by = c("p2" = "id"),
            suffix = c("", ".p2"))
}

df2 <- df2 %>%
  filter(!is.na(p1) & p1!=0)

df2$rand_assignment <- sample(1:2, size = nrow(df2), replace = TRUE)
child_values_to_grab<-list("a.3way","a.2way","b.3way","b.2way")
for (cv in child_values_to_grab){
  P1<-paste0("P1",cv)
  P2<-paste0("P2",cv)
  P1_n<-paste0(P1,".rand")
  P2_n<-paste0(P2,".rand")
  df2<-df2 %>%
  rowwise() %>%
    mutate(tmp = list(sample(c(!!sym(P1),!!sym(P2))))) %>%
    mutate(!!P1_n := tmp[1], !!P2_n := tmp[2]) %>%
  dplyr::select(-c(tmp))
}

###Quick Counts
df2 %>%
  group_by(coh) %>%
  summarise(
    n_greater = sum(P1a.2way > P2a.2way),
    n_total = n(),
    proportion = mean(P1a.2way > P2a.2way)
  )
```
########################
#Figure 1
########################

```{r admixtureplot}

library(ggplot2)
library(dplyr)
library(tidyr)
library(purrr)
library(RColorBrewer)
library(ggh4x)

q<-read.table("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/admixture_analysis/TRIOS_HGDP_all_chrs_bfile_ldpruned.3.Q", header = FALSE)
fam<-read.table("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/admixture_analysis/TRIOS_HGDP_all_chrs_bfile_ldpruned.fam", header = FALSE)

pop_assign<-fam%>%
  dplyr::select(c(V2))
pop_assign <- pop_assign %>%
  separate(V2,    into = c("coh", "id"),
    sep = "_",    extra = "merge",    fill = "right"  )%>%
  mutate(coh = case_when(
    coh == "HGDP" ~ "NAM",
    TRUE ~ coh
  )
  )

# Define population order (edit as needed)
pop_order <- c("YRI","IBS","NAM",
                          "ACB","ASW","CLM","MXL","PEL","PUR")
# Rename ADMIXTURE clusters
colnames(q) <- paste0("K", seq_len(ncol(q)))

q$Population <- factor(
  toupper(pop_assign$coh),
  levels = pop_order
)

pop_meta <- tibble(
  Population = c(
  "YRI","IBS","NAM",
  "ACB","ASW",
  "CLM","MXL","PEL","PUR"
  ),
  Type = c(
  "Reference","Reference","Reference",
  "Admixed Population","Admixed Population",
  "Admixed Population","Admixed Population","Admixed Population","Admixed Population"
  )
)
q <- q %>%
  arrange(
    Population,
    desc(K1),
    desc(K3),
    desc(K2)
    )

q <- q %>%
  left_join(pop_meta, by = "Population")

# Re-number individuals after sorting
q$Individual <- seq_len(nrow(q))

type_order <- c(
  "Reference",
  "Admixed Population"
)
q <- q %>%
  mutate(
    Type = factor(Type, levels = type_order)
)

q_long <- q %>%
  pivot_longer(
    starts_with("K"),
    names_to = "Cluster",
    values_to = "Ancestry"
  )

cols <- colorRampPalette(
  brewer.pal(4, "Accent")
)(length(unique(q_long$Cluster)))

p_admixture<-ggplot(q_long,aes(x = Individual,y = Ancestry,fill = Cluster)) +
  geom_col(width = 1) +
  scale_x_continuous(expand = c(0, 0))+
  theme_professional()+
  facet_nested(
    ~ Type+factor(Population,levels= c(
  "YRI","IBS","NAM",
  "ACB","ASW",
  "CLM","MXL","PEL","PUR"
  )),
    scales = "free_x",
    space = "free_x"
  )+
  theme(legend.position = "none",axis.ticks.x = element_blank(),axis.text.x = element_blank(),
        panel.spacing = unit(0, "lines"),strip.text = element_text(size=25),axis.title = element_text(size=25))

p_admixture

```
```{r df_children_only_and_randoming}
p1<-quick_point_base(df2,x=`P1b.2way`,y=`P2b.2way`,color = coh)+
  labs(y="Inferred P2 (YRI-Like)",col="Population",x="Inferred P1 (YRI-Like)")
p2<-quick_point_base(df2,`P1b.2way.rand`,`P2b.2way.rand`,color = coh)+
  labs(y="Random Inferred P2 (YRI-Like)",col="Population",x="Random Inferred P1 (YRI-Like)")
p3<-quick_point_base(df2,`a3.p1`,`a3.p2`,color = coh)+
  labs(y="Mother (YRI-Like)",col="Population",x="Father (YRI-Like)")
t<-df2
t$t<-ifelse(df2$P1a.2way>df2$P2a.2way,1,0)
t%>%
  group_by(coh)%>%
  summarise(
    a=sum(t)
  )
(0.63*2)-1
22/32
```

```{r corsym_pearson_df}
col_pairs <- list(
  c("P1b.2way", "P2b.2way"),
  c("P1b.2way.rand", "P2b.2way.rand")
)
library("corsym-main")
#  c("a3.p1", "a3.p2")
group_var <- "coh"
# Calculate correlations within groups
cor_results <- do.call(
  rbind,
  lapply(split(df2, df2[[group_var]]), function(dat) {

    data.frame(
      Population = dat[[group_var]][1],
      var1 = sapply(col_pairs, `[`, 1),
      var2 = sapply(col_pairs, `[`, 2),
      pear = sapply(col_pairs, function(pair) {
        cor(
          dat[[pair[1]]],
          dat[[pair[2]]],
          use = "complete.obs"
        )
      }),
      corsym = sapply(col_pairs, function(pair) {
        corsym(
          dat[[pair[1]]],
          dat[[pair[2]]]
        )
      }),
      n = sapply(col_pairs, function(pair) {
        sum(complete.cases(dat[, pair]))
      })
      )
  })
)
type_name<-c("Raw","Random")
cor_results$type <- rep(type_name, length.out = nrow(cor_results))

df_t<-df2
P1<-"P1b.2way"
P2<-"P2b.2way"
cor_results_2 <- list()
for (rep in 1:100) {

  tmp_df <- df_t %>%
      rowwise() %>%
        mutate(tmp = list(sample(c(!!sym(P1),!!sym(P2))))) %>%
        transmute(
          new1  := tmp[1],
          new2  := tmp[2],
          coh = coh
        )%>%
      ungroup()

  for (pop in unique(tmp_df$coh)){
      cor_results_2[[length(cor_results_2) + 1]] <-
      data.frame(
        group = pop,
        original_col1 = P1,
        original_col2 = P2,
        replicate = rep,
        correlation = cor(
          subset(tmp_df,coh==pop)$new1,
          subset(tmp_df,coh==pop)$new2
        ),
        correlation_corsym = corsym(
          subset(tmp_df,coh==pop)$new1,
          subset(tmp_df,coh==pop)$new2
        )
      )
  }
}

cor_results_2 <- bind_rows(cor_results_2)
colnames(cor_results_2)<-c("Population","var1","var2","rep","pear","corsym")
cor_results_2$type<-"Random"
t<-bind_rows(cor_results,cor_results_2)

###Quick Stats
q_stats<-t%>%
  group_by(type,Population)%>%
  summarise(m_p=mean(pear),
            m_c=mean(corsym)
            )
q_stats[,3:4]<-round(q_stats[,3:4],digits=3)
q_stats%>%pivot_wider(
    names_from = c(type),    # Column containing the future header names
    values_from = c(m_p)   # Column containing the cell values
  )


```

```{r Fig1F}
x_labels <- t %>%
  filter(type=="Raw"&!is.na(n))%>%
  mutate(
    label = ifelse(is.na(n),
                   Population,
                   paste0(Population, "\nN=", n))
  )


p_boxplot_fig1<-t %>%
  pivot_longer(
    cols = c(pear, corsym),
    names_to = "Correlation",
    values_to = "value"
  )%>%
  filter(
    !(Correlation == "corsym" & type=="Random")
    )%>%
    mutate(type_group=case_when(
    Correlation=="corsym"~"CorSym",
    type=="Random"&Correlation=="pear"~"Pearson - Data Randomized",
    type=="Raw"&Correlation=="pear"~"Pearson - Original Data",
    TRUE ~ "NA")
    )%>%
  ggplot(., aes(x = Population, y = value,colour = type_group)) +
  geom_boxplot(size=2)+
  geom_hline(yintercept = 0,linetype='dashed',linewidth=3,color="black")+
  labs(y="Computed r (YRI-Like)")+
  scale_x_discrete(
    labels = setNames(x_labels$label, x_labels$Population)
  )+
  scale_color_manual(name="Estimation", values=c("#4E79A7","#F28E2B","#59A14F"))+
  theme_professional(base_size = 30)+
  theme(legend.position = "bottom",panel.border=element_rect(linewidth = 3))
```
```{r fig1e}
p_rc_v_rp_fig1<-cor_results%>%
  dplyr::select(-c("var1","var2","pear"))%>%
  pivot_wider(names_from = type,values_from = corsym)%>%
  ggplot(.,aes(Raw,Random,colour = Population))+
           geom_point(size=6)+
  theme_professional(base_size = 30)+
  geom_abline(intercept = 0,slope=1,linetype="dashed")+
    #scale_y_continuous(limits = c(0,1))+
  labs(y=expression(bold(italic("r"['c']) * " (Inferred Randomized)")),col="Population",x=expression(bold(italic("r"['c']) * " (Inferred)")))+
    theme(legend.position = "none",panel.border = element_rect(linewidth = 3),axis.title = element_text(face="bold"))


```
```{r organize_fig1}
p4<-(p1|p2|p3)+
  plot_annotation()+
  plot_layout(guides = "collect",ncol = 3,nrow = 1) & theme(legend.position = "bottom",legend.text = element_text(size=30),
                                legend.title = element_text(size=30),panel.border=element_rect(linewidth=3))

p_fig1<-p_admixture /
  p4 /
  (p_rc_v_rp_fig1+p_boxplot_fig1+ plot_layout(widths = c(1, 2)))+
  plot_annotation(tag_levels = "A") & theme(
    panel.border=element_rect(linewidth=3),
                                plot.tag = element_text(face = 'bold',size=35),
        strip.background = element_rect(linewidth = 3))

ggsave("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/figures/260720_Figure1.pdf",p_fig1,
       dpi=600,width=29.5,height=29,units="in")

```

########################
#Figure 3
########################

```{r ancestor_admixture_comparison}
col_pairs <- list(
  c("P1b.2way", "P2b.2way"),
  c("a3.p1", "a3.p2")
)
#  c("a3.p1", "a3.p2")
group_var <- "coh"
# Calculate correlations within groups
cor_results <- do.call(
  rbind,
  lapply(split(df2, df2[[group_var]]), function(dat) {

    data.frame(
      Population = dat[[group_var]][1],
      var1 = sapply(col_pairs, `[`, 1),
      var2 = sapply(col_pairs, `[`, 2),
      Pearson = sapply(col_pairs, function(pair) {
        cor(
          dat[[pair[1]]],
          dat[[pair[2]]],
          use = "complete.obs"
        )
      }),
      CorSym = sapply(col_pairs, function(pair) {
        corsym(
          dat[[pair[1]]],
          dat[[pair[2]]]
        )
      }),
      n = sapply(col_pairs, function(pair) {
        sum(complete.cases(dat[, pair]))
      })
      )
  })
)
type_name<-c("ANCESTOR","ADMIXTURE")
cor_results$type <- rep(type_name, length.out = nrow(cor_results))

#p1<-
p_boxplot_fig3<-cor_results %>%
  pivot_longer(
    cols = c(Pearson, CorSym),
    names_to = "Correlation",
    values_to = "value"
  )%>%
  #filter(
  #  !(type=="ANCESTOR" & Correlation == "Pearson")
  #  )%>%
  mutate(type_group=case_when(
    type=="ANCESTOR"&Correlation=="CorSym"~"Inferred - CorSym",
    type=="ANCESTOR"&Correlation=="Pearson"~"Inferred - Pearson",
    type=="ADMIXTURE"&Correlation=="CorSym"~"Real Parent - CorSym",
    type=="ADMIXTURE"&Correlation=="Pearson"~"Real Parent - Pearson",
    TRUE ~ "NA")
 )%>%
  ggplot(., aes(x = Population, y = value,color=type_group)) +
  geom_boxplot(size=3)+
  labs(y="Computed r\n(YRI-Like)")+
  scale_color_manual(name="Estimation", values=c("#4E79A7","#F28E2B","#59A14F","orchid2"))+
  geom_hline(yintercept = 0,linetype='dashed',linewidth=3,color="black")+
  #facet_wrap(~ Population)+
  theme_professional(base_size = 30)+
  theme(legend.position = "bottom",panel.border = element_rect(linewidth=3))
#+  geom_hline(yintercept = 0,linetype="dashed",size=2)

# 
# ggsave("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/plots/ADMIXTURE_corsym_pearson_comparison.png",p1,
#        dpi=600,width=29.5,height=6.7,units="in")
```

```{r Fig3be}
df2$Delta_Adm<-abs(df2$a3.p2-df2$a3.p1)
df2$Delta_Anc.rand<-abs(df2$P2b.2way.rand-df2$P2b.2way.rand)
df2$Delta_Anc<-abs(df2$P2b.2way-df2$P1b.2way)
df2$Mean_Adm<-(df2$a3.p2+df2$a3.p1)/2
#df2$Delta_Anc.rand<-abs(df2$P2b.2way.rand-df2$P2b.2way.rand)
df2$Mean_Anc<-(df2$P2b.2way+df2$P1b.2way)/2

means_df <- df2 %>%
  group_by(coh) %>%
  summarise(
    mean_var1 = mean(Delta_Adm, na.rm = TRUE),
    mean_var2 = mean(Delta_Anc, na.rm = TRUE),
    var_var1  = var(Delta_Adm, na.rm = TRUE),
    var_var2  = var(Delta_Anc, na.rm = TRUE),
    .groups = "drop"
  )

p1<-ggplot(means_df, aes(x = mean_var1, y = mean_var2, color = coh)) +
  geom_point(size = 7) +
    geom_errorbar(
    aes(ymin = mean_var2 - var_var2,
        ymax = mean_var2 + var_var2),
    width = 0,show.legend = FALSE
  ) +
  geom_errorbarh(
    aes(xmin = mean_var1 - var_var1,
        xmax = mean_var1 + var_var1),show.legend = FALSE,
    height = 0
  ) +
  labs(x="Mean Difference\n(True Parents, YRI-Like)",y="Mean Difference\n(Inferred Parents, YRI-Like)")+
  #geom_hline(yintercept = 0)+
  #geom_vline(xintercept = 0)+
  theme_professional(base_size = 30)+
  scale_color_discrete(name="Population")+
  geom_abline(slope=1,size=2,linetype="dashed")+
  theme(legend.position = "none",panel.border=element_rect(linewidth = 3))+
  scale_x_continuous(limits = c(0,.2))+
  scale_y_continuous(limits=c(0,.2))


p2<-ggplot(df2, aes(x = Mean_Adm, y = Mean_Anc, color = coh)) +
  geom_point(size = 7) +
  labs(x="Avg. Ancestry\n(True Parents, YRI-Like)",y="Avg. Ancestry\n(Inferred Parents, YRI-Like)")+
  scale_color_discrete(name="Population")+
  geom_abline(slope=1,size=2,linetype="dashed")+
  theme_professional(base_size = 30)+
  theme(panel.border=element_rect(linewidth = 3))

p3<-(p1+p2+ plot_layout(widths = c(1,1))) /
  p_boxplot_fig3+
  plot_annotation(tag_levels = "A") & theme(
    panel.border=element_rect(linewidth=3),
                                plot.tag = element_text(face = 'bold',size=35),
        strip.background = element_rect(linewidth = 3))

ggsave("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/figures/260720_Figure3.pdf",p3,
       dpi=600,width=29.5,height=23,units="in")
```


####################
##########Figure 4
####################
```{r test}
p1<-df2%>%
  select(c(a3.p1, a3.p2,coh))%>%
  pivot_longer(
    cols = c(a3.p1, a3.p2),
    names_to = "Parent",
    values_to = "value"
  )%>%
  mutate(Parent=case_when(
    Parent=="a3.p1"~"Father",
    Parent=="a3.p2"~"Mother",
    TRUE ~ "NA")
  )%>%
  filter(!is.na(value))%>%
  ggplot(.)+
  geom_boxplot(aes(y=`value`,fill=Parent,x=coh,col=after_scale(fill)),size=2,alpha=.5)+
  labs(y="True Ancestry (YRI-Like)",x="Population")+
  scale_fill_manual(name="Parent", values=c("#00FFCC","#FF9933"))+
  theme_professional(base_size = 30)+
  theme(legend.position = "bottom",panel.border=element_rect(linewidth = 3))+
  plot_annotation(tag_levels = "A") & theme(legend.position = "bottom",legend.text = element_text(size=30),
                                legend.title = element_text(size=30),panel.border=element_rect(linewidth=3),
                                plot.tag = element_text(face = 'bold',size=35))

ggsave("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/figures/260715_Figure4.pdf",p1,
       dpi=600,width=29.5,height=10,units="in")


ks_test_set<-df2%>%
  select(c(a3.p1, a3.p2,coh))%>%
  pivot_longer(
    cols = c(a3.p1, a3.p2),
    names_to = "Parent",
    values_to = "value"
  )%>%
  mutate(Parent=case_when(
    Parent=="a3.p1"~"Father",
    Parent=="a3.p2"~"Mother",
    TRUE ~ "NA")
  )%>%
  filter(!is.na(value))
for(pop in unique(ks_test_set$coh)){
  ks_test_output<-ks.test(subset(ks_test_set,(coh==pop&Parent=="Father"))$value,
          subset(ks_test_set,(coh==pop&Parent=="Mother"))$value,alternative = "two.sided")
  print(paste0(pop," had a p-value of: ",ks_test_output$p.value))
}

```

##############
##Supplemental Figure Data
##############

```{r threeway data}
parent_values_to_grab<-list("a1","a2","a3","a_NonYRI","0","1","2")
df2<-df
df2<-na.omit(df2)
for (pv in parent_values_to_grab){
  df2<-df2%>%
    left_join(df %>% dplyr::select(id, pv),
            by = c("p1" = "id"),
            suffix = c("", ".p1"))
}
for (pv in parent_values_to_grab){
  df2<-df2%>%
    left_join(df %>% dplyr::select(id, pv),
            by = c("p2" = "id"),
            suffix = c("", ".p2"))
}

df2 <- df2 %>%
  filter(!is.na(p1) & p1!=0)

df2$rand_assignment <- sample(1:2, size = nrow(df2), replace = TRUE)
child_values_to_grab<-list("a.3way","b.3way","c.3way")
for (cv in child_values_to_grab){
  P1<-paste0("P1",cv)
  P2<-paste0("P2",cv)
  P1_n<-paste0(P1,".rand")
  P2_n<-paste0(P2,".rand")
  df2<-df2 %>%
  rowwise() %>%
    mutate(tmp = list(sample(c(!!sym(P1),!!sym(P2))))) %>%
    mutate(!!P1_n := tmp[1], !!P2_n := tmp[2]) %>%
  dplyr::select(-c(tmp))
}
df2$Delta_Adm.NAM<-abs(df2$a1.p2-df2$a1.p1)
df2$Delta_Adm.IBS<-abs(df2$a2.p2-df2$a2.p1)
df2$Delta_Anc.IBS<-abs(df2$P2b.3way-df2$P1b.3way)
df2$Delta_Anc.NAM<-abs(df2$P2a.3way-df2$P1a.3way)
df2$Delta_Adm.YRI<-abs(df2$a3.p2-df2$a3.p1)
df2$Delta_Anc.YRI<-abs(df2$P2c.3way-df2$P1c.3way)

means_df <- df2 %>%
  group_by(coh) %>%
  summarise(
    mean_var1.NAM = mean(Delta_Adm.NAM, na.rm = TRUE),
    mean_var1.IBS = mean(Delta_Adm.IBS, na.rm = TRUE),
    mean_var2.IBS = mean(Delta_Anc.IBS, na.rm = TRUE),
    mean_var2.NAM = mean(Delta_Anc.NAM, na.rm = TRUE),
    var_var1.NAM  = var(Delta_Adm.NAM, na.rm = TRUE),
    var_var2.NAM  = var(Delta_Anc.NAM, na.rm = TRUE),
    var_var1.IBS  = var(Delta_Adm.IBS, na.rm = TRUE),
    var_var2.IBS  = var(Delta_Anc.IBS, na.rm = TRUE),  
    mean_var1.YRI = mean(Delta_Adm.YRI, na.rm = TRUE),
    mean_var2.YRI = mean(Delta_Anc.YRI, na.rm = TRUE),
    var_var1.YRI  = var(Delta_Adm.YRI, na.rm = TRUE),
    var_var2.YRI  = var(Delta_Anc.YRI, na.rm = TRUE),      
    .groups = "drop"
  )

t<-df2
t<-t%>%
  mutate(YRI=ifelse(P1c.3way>P2c.3way,1,0),
         NAM=ifelse(P1a.3way>P2a.3way,1,0),
         IBS=ifelse(P1b.3way>P2b.3way,1,0),
         n_coh = n())
t2<-t%>%  
group_by(coh)%>%
  summarise(
    YRI_2=sum(YRI),
    NAM_2=sum(NAM),
    IBS_2=sum(IBS),
    n=n()
  )%>%
  mutate(YRI_3=n-YRI_2,
         NAM_3=n-NAM_2,
         IBS_3=n-IBS_2,
        p_a1=(pmax(YRI_2,YRI_3)/n)*2-1,
         p_a2=(pmax(NAM_2,NAM_3)/n)*2-1,
         p_a3=(pmax(IBS_2,IBS_3)/n)*2-1)

  
sum(t2$a3)
t2
t2<-t2%>%
  select(.,-c(YRI_3,IBS_3,NAM_3))
write.table(t2, file = "C:/Users/Ictinike/Downloads/output.txt")

```



##############
##Supplemental Figure 1
##############

```{r sup1_plots}
p1<-quick_point_base(df2,`P1b.3way`,`P2b.3way`,color = coh,point_size = 5)+
  labs(y="Inferred P2 (IBS-Like)",col="Population",x="Inferred P1 (IBS-Like)")+
    theme(legend.position = "none")
p1
p2<-quick_point_base(df2,`P1a.3way`,`P2a.3way`,color = coh,point_size = 5)+
  labs(y="Inferred P2 (NAM-Like)",col="Population",x="Inferred P1 (NAM-Like)")+
    theme(legend.position = "none")
p2
p3<-quick_point_base(df2,`P1c.3way`,`P2c.3way`,color = coh,point_size = 5)+
  labs(y="Inferred P2 (YRI-Like)",col="Population",x="Inferred P1 (YRI-Like)")+
    theme(legend.position = "none")
p3
p4<-quick_point_base(means_df,mean_var1.IBS,mean_var2.IBS,color = coh,point_size = 5)+
    geom_errorbar(
    aes(ymin = mean_var2.IBS - var_var2.IBS,
        ymax = mean_var2.IBS + var_var2.IBS),
    width = 0,show.legend = FALSE
  ) +
  geom_errorbarh(
    aes(xmin = mean_var1.IBS - var_var1.IBS,
        xmax = mean_var1.IBS + var_var1.IBS),show.legend = FALSE,
    height = 0
  ) +
  labs(x="Mean Difference\n(True Parents, IBS-Like)",y="Mean Difference\n(Inferred Parents, IBS-Like)",color="Population")+
  theme(legend.position = "none")+
  scale_x_continuous(limits = c(0,.3))+
  scale_y_continuous(limits=c(0,.3))+
  guides(color="none")
p5<-quick_point_base(means_df,mean_var1.NAM,mean_var2.NAM,color = coh,point_size = 5)+
    geom_errorbar(
    aes(ymin = mean_var2.NAM - var_var2.NAM,
        ymax = mean_var2.NAM + var_var2.NAM),
    width = 0,show.legend = FALSE
  ) +
  geom_errorbarh(
    aes(xmin = mean_var1.NAM - var_var1.NAM,
        xmax = mean_var1.NAM + var_var1.NAM),show.legend = FALSE,
    height = 0
  ) +
  labs(x="Mean Difference\n(True Parents, NAM-Like)",y="Mean Difference\n(Inferred Parents, NAM-Like)",color="Population")+
  theme(legend.position = "none")+
  scale_x_continuous(limits = c(0,.3))+
  scale_y_continuous(limits=c(0,.3))+
  guides(color="none")
p6<-quick_point_base(means_df,mean_var1.YRI,mean_var2.YRI,color = coh,point_size = 5)+
    geom_errorbar(
    aes(ymin = mean_var2.YRI - var_var2.YRI,
        ymax = mean_var2.YRI + var_var2.YRI),
    width = 0,show.legend = FALSE
  ) +
  geom_errorbarh(
    aes(xmin = mean_var1.YRI - var_var1.YRI,
        xmax = mean_var1.YRI + var_var1.YRI),show.legend = FALSE,
    height = 0
  ) +
  labs(x="Mean Difference\n(True Parents, YRI-Like)",y="Mean Difference\n(Inferred Parents, YRI-Like)",color="Population")+
  theme(legend.position = "none")+
  scale_x_continuous(limits = c(0,.3))+
  scale_y_continuous(limits=c(0,.3))+
  guides(color="none")
```
```{r plot_figsup1}
p7<-(p3|p6|p1|p4|p2|p5)+
  plot_annotation(tag_levels = "A")+
  plot_layout(guides = "collect",ncol = 2,nrow = 3) & theme(legend.position = "bottom",legend.text = element_text(size=30),
                                legend.title = element_text(size=30),
                                panel.border=element_rect(linewidth=3),
                                plot.tag = element_text(face = 'bold',size=35))


ggsave("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/figures/260720_Supplemental_Fig1.pdf",p7,
       dpi=600,width=20,height=25,units="in")
```

##############
##Supplemental Figure 2, Population Computed R Comparison
##############

```{r ancestor_admixture_comparison}
col_pairs <- list(
  c("P1a.3way", "P2a.3way"),
  c("a1.p1", "a1.p2")
)

group_var <- "coh"

cor_results <- do.call(
  rbind,
  lapply(split(df2, df2[[group_var]]), function(dat) {

    data.frame(
      Population = dat[[group_var]][1],
      var1 = sapply(col_pairs, `[`, 1),
      var2 = sapply(col_pairs, `[`, 2),
      Pearson = sapply(col_pairs, function(pair) {
        cor(
          dat[[pair[1]]],
          dat[[pair[2]]]
        )
      }),
      CorSym = sapply(col_pairs, function(pair) {
        corsym(
          dat[[pair[1]]],
          dat[[pair[2]]]
        )
      }),
      n = sapply(col_pairs, function(pair) {
        sum(complete.cases(dat[, pair]))
      })
      )
  })
)
cor_results[is.na(cor_results)] <- 0
type_name<-c("ANCESTOR","ADMIXTURE")
cor_results$type <- rep(type_name, length.out = nrow(cor_results))

#p1<-
p1<-cor_results %>%
  pivot_longer(
    cols = c(Pearson, CorSym),
    names_to = "Correlation",
    values_to = "value"
  )%>%
  mutate(type_group=case_when(
    type=="ANCESTOR"&Correlation=="CorSym"~"Inferred - CorSym",
    type=="ANCESTOR"&Correlation=="Pearson"~"Inferred - Pearson",
    type=="ADMIXTURE"&Correlation=="CorSym"~"Real Parent - CorSym",
    type=="ADMIXTURE"&Correlation=="Pearson"~"Real Parent - Pearson",
    TRUE ~ "NA")
 )%>%
  ggplot(., aes(x = Population, y = value,color=type_group)) +
  scale_y_continuous(limits = c(-.25,1,.25))+
  geom_boxplot(size=3)+
  labs(y="Computed R\n(NAM-Like)")+
  geom_hline(yintercept = 0,linetype='dashed',linewidth=3,color="black")+
  scale_color_manual(name="Estimation", values=c("#4E79A7","#F28E2B","#59A14F","orchid2"))+
  theme_professional(base_size = 30)+
  theme(legend.position = "bottom",panel.border = element_rect(linewidth=3))


col_pairs <- list(
  c("P1b.3way", "P2b.3way"),
  c("a2.p1", "a2.p2")
)

group_var <- "coh"

# Calculate correlations within groups
cor_results <- do.call(
  rbind,
  lapply(split(df2, df2[[group_var]]), function(dat) {

    data.frame(
      Population = dat[[group_var]][1],
      var1 = sapply(col_pairs, `[`, 1),
      var2 = sapply(col_pairs, `[`, 2),
      Pearson = sapply(col_pairs, function(pair) {
        cor(
          dat[[pair[1]]],
          dat[[pair[2]]]
        )
      }),
      CorSym = sapply(col_pairs, function(pair) {
        corsym(
          dat[[pair[1]]],
          dat[[pair[2]]]
        )
      }),
      n = sapply(col_pairs, function(pair) {
        sum(complete.cases(dat[, pair]))
      })
      )
  })
)
cor_results[is.na(cor_results)] <- 0
type_name<-c("ANCESTOR","ADMIXTURE")
cor_results$type <- rep(type_name, length.out = nrow(cor_results))

#p1<-
p2<-cor_results %>%
  pivot_longer(
    cols = c(Pearson, CorSym),
    names_to = "Correlation",
    values_to = "value"
  )%>%
  mutate(type_group=case_when(
    type=="ANCESTOR"&Correlation=="CorSym"~"Inferred - CorSym",
    type=="ANCESTOR"&Correlation=="Pearson"~"Inferred - Pearson",
    type=="ADMIXTURE"&Correlation=="CorSym"~"Real Parent - CorSym",
    type=="ADMIXTURE"&Correlation=="Pearson"~"Real Parent - Pearson",
    TRUE ~ "NA")
 )%>%
  ggplot(., aes(x = Population, y = value,color=type_group)) +
  scale_y_continuous(limits = c(-.25,1,.25))+
  geom_boxplot(size=3)+
  labs(y="Computed R\n(IBS-Like)")+
  scale_color_manual(name="Estimation", values=c("#4E79A7","#F28E2B","#59A14F","orchid2"))+
  geom_hline(yintercept = 0,linetype='dashed',linewidth=3,color="black")+
  theme_professional(base_size = 30)+
  theme(legend.position = "bottom",panel.border = element_rect(linewidth=3))
#+  geom_hline(yintercept = 0,linetype="dashed",size=2)


col_pairs <- list(
  c("P1c.3way", "P2c.3way"),
  c("a3.p1", "a3.p2")
)

group_var <- "coh"

# Calculate correlations within groups
cor_results <- do.call(
  rbind,
  lapply(split(df2, df2[[group_var]]), function(dat) {

    data.frame(
      Population = dat[[group_var]][1],
      var1 = sapply(col_pairs, `[`, 1),
      var2 = sapply(col_pairs, `[`, 2),
      Pearson = sapply(col_pairs, function(pair) {
        cor(
          dat[[pair[1]]],
          dat[[pair[2]]]
        )
      }),
      CorSym = sapply(col_pairs, function(pair) {
        corsym(
          dat[[pair[1]]],
          dat[[pair[2]]]
        )
      }),
      n = sapply(col_pairs, function(pair) {
        sum(complete.cases(dat[, pair]))
      })
      )
  })
)
cor_results[is.na(cor_results)] <- 0
type_name<-c("ANCESTOR","ADMIXTURE")
cor_results$type <- rep(type_name, length.out = nrow(cor_results))

#p1<-
p3<-cor_results %>%
  pivot_longer(
    cols = c(Pearson, CorSym),
    names_to = "Correlation",
    values_to = "value"
  )%>%
  mutate(type_group=case_when(
    type=="ANCESTOR"&Correlation=="CorSym"~"Inferred - CorSym",
    type=="ANCESTOR"&Correlation=="Pearson"~"Inferred - Pearson",
    type=="ADMIXTURE"&Correlation=="CorSym"~"Real Parent - CorSym",
    type=="ADMIXTURE"&Correlation=="Pearson"~"Real Parent - Pearson",
    TRUE ~ "NA")
 )%>%
  ggplot(., aes(x = Population, y = value,color=type_group)) +
  scale_y_continuous(limits = c(-.25,1,.25))+
  geom_boxplot(size=3)+
  labs(y="Computed R\n(YRI-Like)")+
  scale_color_manual(name="Estimation", values=c("#4E79A7","#F28E2B","#59A14F","orchid2"))+
  theme_professional(base_size = 30)+
  geom_hline(yintercept = 0,linetype='dashed',linewidth=3,color="black")+
  theme(legend.position = "bottom",panel.border = element_rect(linewidth=3))

p4<-(p3|p2|p1)+
  plot_annotation(tag_levels = "A")+
  plot_layout(guides = "collect",ncol = 1,nrow = 3) & theme(legend.position = "bottom",legend.text = element_text(size=30),
                                legend.title = element_text(size=30),panel.border=element_rect(linewidth=3),
                                plot.tag = element_text(face = 'bold',size=35))

ggsave("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/figures/260720Supplemental_Figure2.pdf",p4,
       dpi=600,width=29.5,height=15,units="in")

```

##############
##Supplemental Figure 3, Parent Means
##############


```{r mean_test}
p_rf_YRI<-quick_point_base(df2,`2`,a3,color = coh,point_size = 5)+
  labs(x="RFmix (Child, YRI-Like)",y="ADMIXTURE\n(Child, YRI-Like)",col="Population")
p_rf_IBS<-quick_point_base(df2,`1`,a2,color = coh,point_size = 5)+
  labs(x="RFmix (Child, IBS-Like)",y="ADMIXTURE\n(Child, IBS-Like)",col="Population")
p_rf_NAM<-quick_point_base(df2,`0`,a1,color = coh,point_size = 5)+
  labs(x="RFmix (Child, NAM-Like)",y="ADMIXTURE\n(Child, NAM-Like)",col="Population")

parent_values_to_grab<-list("a1","a2","a3","a_NonYRI","0","1","2")
df2<-df
for (pv in parent_values_to_grab){
  df2<-df2%>%
    left_join(df %>% dplyr::select(id, pv),
            by = c("p1" = "id"),
            suffix = c("", ".p1"))
}
for (pv in parent_values_to_grab){
  df2<-df2%>%
    left_join(df %>% dplyr::select(id, pv),
            by = c("p2" = "id"),
            suffix = c("", ".p2"))
}

df2 <- df2 %>%
  filter(!is.na(p1) & p1!=0)

df2$rand_assignment <- sample(1:2, size = nrow(df2), replace = TRUE)
child_values_to_grab<-list("a.3way","b.3way","c.3way")
for (cv in child_values_to_grab){
  P1<-paste0("P1",cv)
  P2<-paste0("P2",cv)
  P1_n<-paste0(P1,".rand")
  P2_n<-paste0(P2,".rand")
  df2<-df2 %>%
  rowwise() %>%
    mutate(tmp = list(sample(c(!!sym(P1),!!sym(P2))))) %>%
    mutate(!!P1_n := tmp[1], !!P2_n := tmp[2]) %>%
  dplyr::select(-c(tmp))
}
df2 <- df2 %>%
  filter(!is.na(p1) & p1!=0)

df2$rand_assignment <- sample(1:2, size = nrow(df2), replace = TRUE)
child_values_to_grab<-list("a.3way","b.3way","c.3way")
for (cv in child_values_to_grab){
  P1<-paste0("P1",cv)
  P2<-paste0("P2",cv)
  P1_n<-paste0(P1,".rand")
  P2_n<-paste0(P2,".rand")
  df2<-df2 %>%
  rowwise() %>%
    mutate(tmp = list(sample(c(!!sym(P1),!!sym(P2))))) %>%
    mutate(!!P1_n := tmp[1], !!P2_n := tmp[2]) %>%
  dplyr::select(-c(tmp))
}
df2$Delta_Adm.NAM<-abs(df2$a1.p2-df2$a1.p1)
df2$Delta_Adm.IBS<-abs(df2$a2.p2-df2$a2.p1)
df2$Delta_Anc.IBS<-abs(df2$P2b.3way-df2$P1b.3way)
df2$Delta_Anc.NAM<-abs(df2$P2a.3way-df2$P1a.3way)
df2$Delta_Adm.YRI<-abs(df2$a3.p2-df2$a3.p1)
df2$Delta_Anc.YRI<-abs(df2$P2c.3way-df2$P1c.3way)
df2$Delta_Adm.NAM<-abs(df2$a1.p2+df2$a1.p1)/2
df2$Delta_Adm.IBS<-abs(df2$a2.p2+df2$a2.p1)/2
df2$Delta_Anc.IBS<-abs(df2$P2b.3way+df2$P1b.3way)/2
df2$Delta_Anc.NAM<-abs(df2$P2a.3way+df2$P1a.3way)/2
df2$Delta_Adm.YRI<-abs(df2$a3.p2+df2$a3.p1)/2
df2$Delta_Anc.YRI<-abs(df2$P2c.3way+df2$P1c.3way)/2

p1<-ggplot(df2, aes(x = Delta_Anc.IBS, y = a2, color = coh)) +
  geom_point(size = 7) +
  labs(x="Mean Parent Ancestry\n(Inferred Parents, IBS-Like)",y="Child Ancestry\n(True Ancestry, IBS-Like)")+
  theme_professional(base_size = 30)+
  scale_color_discrete(name="Population")+
  geom_abline(slope=1,size=2,linetype="dashed")+
  theme(legend.position = "none",panel.border=element_rect(linewidth = 3))+
  xlim(0, 1)+
  ylim(0, 1)
p2<-ggplot(df2, aes(x = Delta_Anc.NAM, y = a1, color = coh)) +
  geom_point(size = 7) +
  labs(x="Mean Parent Ancestry\n(Inferred Parents, NAM-Like)",y="Child Ancestry\n(True Ancestry, NAM-Like)")+  theme_professional(base_size = 30)+
  scale_color_discrete(name="Population")+
  geom_abline(slope=1,size=2,linetype="dashed")+
  theme(legend.position = "none",panel.border=element_rect(linewidth = 3))+
  xlim(0, 1)+
  ylim(0, 1)
p3<-ggplot(df2, aes(x = Delta_Anc.YRI, y = a3, color = coh)) +
  geom_point(size = 7) +
  labs(x="Mean Parent Ancestry\n(Inferred Parents, YRI-Like)",y="Child Ancestry\n(True Ancestry, YRI-Like)")+  theme_professional(base_size = 30)+
  scale_color_discrete(name="Population")+
  geom_abline(slope=1,size=2,linetype="dashed")+
  theme(legend.position = "none",panel.border=element_rect(linewidth = 3))+
  xlim(0, 1)+
  ylim(0, 1)
p4<-ggplot(df2, aes(x = Delta_Adm.IBS, y = a2, color = coh)) +
  geom_point(size = 7) +
  labs(x="Mean Parent Ancestry\n(True Parents, IBS-Like)",y="Child Ancestry\n(True Ancestry, IBS-Like)")+  theme_professional(base_size = 30)+
  scale_color_discrete(name="Population")+
  geom_abline(slope=1,size=2,linetype="dashed")+
  theme(legend.position = "none",panel.border=element_rect(linewidth = 3))+
  xlim(0, 1)+
  ylim(0, 1)
p5<-ggplot(df2, aes(x = Delta_Adm.NAM, y = a1, color = coh)) +
  geom_point(size = 7) +
  labs(x="Mean Parent Ancestry\n(True Parents, NAM-Like)",y="Child Ancestry\n(True Ancestry, NAM-Like)")+   theme_professional(base_size = 30)+
  scale_color_discrete(name="Population")+
  geom_abline(slope=1,size=2,linetype="dashed")+
  theme(legend.position = "none",panel.border=element_rect(linewidth = 3))+
  xlim(0, 1)+
  ylim(0, 1) 
p6<-ggplot(df2, aes(x = Delta_Adm.YRI, y = a3, color = coh)) +
  geom_point(size = 7) +
  labs(x="Mean Parent Ancestry\n(True Parents, YRI-Like)",y="Child Ancestry\n(True Ancestry, YRI-Like)")+   theme_professional(base_size = 30)+
  scale_color_discrete(name="Population")+
  geom_abline(slope=1,size=2,linetype="dashed")+
  theme(legend.position = "none",panel.border=element_rect(linewidth = 3))+
  xlim(0, 1)+
  ylim(0, 1) 
p7<-(p_rf_YRI|p6|p3|p_rf_IBS|p4|p1|p_rf_NAM|p5|p2)+
  plot_annotation(tag_levels = "A")+
  plot_layout(guides = "collect",ncol = 3,nrow = 3) & theme(legend.position = "bottom",legend.text = element_text(size=30),
                                legend.title = element_text(size=30),panel.border=element_rect(linewidth=3),
                                plot.tag = element_text(face = 'bold',size=35))

#p4
ggsave("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/figures/260720Supplemental_Figure3.pdf",p7,
      dpi=600,width=29.5,height=29,units="in")
```

####################
##Supplemental Figure 4
####################
```{r test}
p1<-df2%>%
  select(c(a3.p1, a3.p2,coh))%>%
  pivot_longer(
    cols = c(a3.p1, a3.p2),
    names_to = "Parent",
    values_to = "value"
  )%>%
  mutate(Parent=case_when(
    Parent=="a3.p1"~"Father",
    Parent=="a3.p2"~"Mother",
    TRUE ~ "NA")
  )%>%
  filter(!is.na(value))%>%
  ggplot(.)+
  geom_boxplot(aes(y=`value`,fill=Parent,x=coh,col=after_scale(fill)),size=2,alpha=.5)+
  labs(y="True Ancestry\n(YRI-Like)",x="Population")+
  scale_fill_manual(name="Parent", values=c("#00FFCC","#FF9933"))+
  theme_professional(base_size = 30)+
  theme(legend.position = "bottom",panel.border=element_rect(linewidth = 3))

p2<-df2%>%
  select(c(a2.p1, a2.p2,coh))%>%
  pivot_longer(
    cols = c(a2.p1, a2.p2),
    names_to = "Parent",
    values_to = "value"
  )%>%
  mutate(Parent=case_when(
    Parent=="a2.p1"~"Father",
    Parent=="a2.p2"~"Mother",
    TRUE ~ "NA")
  )%>%
  filter(!is.na(value))%>%
  ggplot(.)+
  geom_boxplot(aes(y=`value`,fill=Parent,x=coh,col=after_scale(fill)),size=2,alpha=.5)+
  labs(y="True Ancestry\n(IBS-Like)",x="Population")+
  scale_fill_manual(name="Parent", values=c("#00FFCC","#FF9933"))+
  theme_professional(base_size = 30)+
  theme(legend.position = "bottom",panel.border=element_rect(linewidth = 3))

p3<-df2%>%
  select(c(a1.p1, a1.p2,coh))%>%
  pivot_longer(
    cols = c(a1.p1, a1.p2),
    names_to = "Parent",
    values_to = "value"
  )%>%
  mutate(Parent=case_when(
    Parent=="a1.p1"~"Father",
    Parent=="a1.p2"~"Mother",
    TRUE ~ "NA")
  )%>%
  filter(!is.na(value))%>%
  ggplot(.)+
  geom_boxplot(aes(y=`value`,fill=Parent,x=coh,col=after_scale(fill)),size=2,alpha=.5)+
  labs(y="True Ancestry\n(NAM-Like)",x="Population")+
  scale_fill_manual(name="Parent", values=c("#00FFCC","#FF9933"))+
  theme_professional(base_size = 30)+
  theme(legend.position = "bottom",panel.border=element_rect(linewidth = 3))

  
p4<-(p1|p2|p3)+
  plot_annotation(tag_levels = "A")+
  plot_layout(guides = "collect",ncol = 1,nrow = 3) & theme(legend.position = "bottom",legend.text = element_text(size=30),
                                legend.title = element_text(size=30),panel.border=element_rect(linewidth=3),
                                plot.tag = element_text(face = 'bold',size=35))

ggsave("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/figures/260715_SuppFigure4.pdf",p4,
       dpi=600,width=29.5,height=20,units="in")


ks_test_set<-df2%>%
  select(c(a3.p1, a3.p2,coh))%>%
  pivot_longer(
    cols = c(a3.p1, a3.p2),
    names_to = "Parent",
    values_to = "value"
  )%>%
  mutate(Parent=case_when(
    Parent=="a3.p1"~"Father",
    Parent=="a3.p2"~"Mother",
    TRUE ~ "NA")
  )%>%
  filter(!is.na(value))
for(pop in unique(ks_test_set$coh)){
  ks_test_output<-ks.test(subset(ks_test_set,(coh==pop&Parent=="Father"))$value,
          subset(ks_test_set,(coh==pop&Parent=="Mother"))$value,alternative = "two.sided")
  print(paste0(pop," for YRI had a p-value of: ",ks_test_output$p.value))
}

ks_test_set<-df2%>%
  select(c(a2.p1, a2.p2,coh))%>%
  pivot_longer(
    cols = c(a2.p1, a2.p2),
    names_to = "Parent",
    values_to = "value"
  )%>%
  mutate(Parent=case_when(
    Parent=="a2.p1"~"Father",
    Parent=="a2.p2"~"Mother",
    TRUE ~ "NA")
  )%>%
  filter(!is.na(value))
for(pop in unique(ks_test_set$coh)){
  ks_test_output<-ks.test(subset(ks_test_set,(coh==pop&Parent=="Father"))$value,
          subset(ks_test_set,(coh==pop&Parent=="Mother"))$value,alternative = "two.sided")
  print(paste0(pop," for IBS had a p-value of: ",ks_test_output$p.value))
}

ks_test_set<-df2%>%
  select(c(a1.p1, a1.p2,coh))%>%
  pivot_longer(
    cols = c(a1.p1, a1.p2),
    names_to = "Parent",
    values_to = "value"
  )%>%
  mutate(Parent=case_when(
    Parent=="a1.p1"~"Father",
    Parent=="a1.p2"~"Mother",
    TRUE ~ "NA")
  )%>%
  filter(!is.na(value))
for(pop in unique(ks_test_set$coh)){
  ks_test_output<-ks.test(subset(ks_test_set,(coh==pop&Parent=="Father"))$value,
          subset(ks_test_set,(coh==pop&Parent=="Mother"))$value,alternative = "two.sided")
  print(paste0(pop," for NAM had a p-value of: ",ks_test_output$p.value))
}
0.05/18

p1<-df2%>%
  select(c(a3.p1, a3.p2,coh))%>%
  pivot_longer(
    cols = c(a3.p1, a3.p2),
    names_to = "Parent",
    values_to = "value"
  )%>%
  mutate(Parent=case_when(
    Parent=="a3.p1"~"Father",
    Parent=="a3.p2"~"Mother",
    TRUE ~ "NA")
  )%>%
  filter(!is.na(value))%>%
  ggplot(.)+
  geom_boxplot(aes(y=`value`,fill=Parent,x=coh,col=after_scale(fill)),size=2,alpha=.5)+
  labs(y="True Ancestry\n(YRI-Like)",x="Population")+
  scale_fill_manual(name="Parent", values=c("#00FFCC","#FF9933"))+
  theme_professional(base_size = 30)+
  theme(legend.position = "bottom",panel.border=element_rect(linewidth = 3))

ggplot(df2)+
  geom_histogram(aes(a3.p1),fill="#00FFCC")+
    geom_histogram(aes(a3.p2),fill="#FF9933")+
  facet_wrap(.~coh)


```

####################
##Supplemental Figure 4, YRI Two-Three Confirmation
####################
```{r test}
parent_values_to_grab<-list("a1","a2","a3","a_NonYRI","0","1","2")
df2<-df
for (pv in parent_values_to_grab){
  df2<-df2%>%
    left_join(df %>% dplyr::select(id, pv),
            by = c("p1" = "id"),
            suffix = c("", ".p1"))
}
for (pv in parent_values_to_grab){
  df2<-df2%>%
    left_join(df %>% dplyr::select(id, pv),
            by = c("p2" = "id"),
            suffix = c("", ".p2"))
}

df2 <- df2 %>%
  filter(!is.na(p1) & p1!=0)

df2$rand_assignment <- sample(1:2, size = nrow(df2), replace = TRUE)
child_values_to_grab<-list("a.3way","b.3way","c.3way","b.2way")
for (cv in child_values_to_grab){
  P1<-paste0("P1",cv)
  P2<-paste0("P2",cv)
  P1_n<-paste0(P1,".rand")
  P2_n<-paste0(P2,".rand")
  df2<-df2 %>%
  rowwise() %>%
    mutate(tmp = list(sample(c(!!sym(P1),!!sym(P2))))) %>%
    mutate(!!P1_n := tmp[1], !!P2_n := tmp[2]) %>%
  dplyr::select(-c(tmp))
}

df2$Mean_Anc.YRI.2<-abs(df2$P2b.2way+df2$P1b.2way)/2
df2$Mean_Anc.YRI.3<-abs(df2$P2c.3way+df2$P1c.3way)/2
df2$Mean_Anc.IBS.2<-abs(df2$P2a.2way+df2$P1a.2way)/2
df2$Mean_Anc.IBS.3<-abs(df2$P2b.3way+df2$P1b.3way)/2
df2$Mean_Anc.NAM.2<-abs(df2$P2a.2way+df2$P1a.2way)/2
df2$Mean_Anc.NAM.3<-abs(df2$P2a.3way+df2$P1a.3way)/2

p1<-quick_point_base(df2,Mean_Anc.YRI.2,Mean_Anc.YRI.3,col=coh,point_size = 5)+
    labs(y="3-Way Mean Inferred Ancestry\n(YRI-Like)",col="Population",x="2-Way Mean Inferred Ancestry\n(YRI-Like)")
p2<-quick_point_base(df2,Mean_Anc.IBS.2,Mean_Anc.IBS.3,col=coh,point_size = 5)+
    labs(y="3-Way Mean Inferred Ancestry\n(IBS-Like)",col="Population",x="2-Way Mean Inferred Ancestry\n(NonYRI-Like)")
p3<-quick_point_base(df2,Mean_Anc.NAM.2,Mean_Anc.NAM.3,col=coh,point_size = 5)+
    labs(y="3-Way Mean Inferred Ancestry\n(NAM-Like)",col="Population",x="2-Way Mean Inferred Ancestry\n(NonYRI-Like)")

p4<-(p1|p2|p3)+
  plot_annotation(tag_levels = "A")+
  plot_layout(guides = "collect",ncol = 3,nrow = 1)& theme(legend.position = "bottom",legend.text = element_text(size=30),
                                legend.title = element_text(size=40),panel.border=element_rect(linewidth=3),
                                plot.tag = element_text(face = 'bold',size=45))

ggsave("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/figures/260720_Supplemental_Figure4_YRI_check.pdf",p4,
       dpi=600,width=45,height=15,units="in")


```

###Cross-Validation ADMIXTURE Curve
```{r crossval}
cv_results <- read.csv("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/admixture_analysis/Cross-validation-curve_TRIOS_HGDP_all_chrs_merged_bfile.txt",sep="\t",header=TRUE)

#cv_results$cv_error<-round(cv_results$cv_error,digits=4)
best <- cv_results[which.min(cv_results$cv_error), ]
p1<-ggplot(cv_results, aes(k, cv_error)) +
  geom_line(linewidth = 1) +
  geom_point(size = 2) +
  geom_vline(xintercept = best$k,
             linetype = "dashed",
             color = "red") +
  geom_point(data = best,
             color = "red",
             size = 3) +
  labs(x="K",y="CV Error")+
    theme_professional()+
  plot_annotation(tag_levels = "A")& 
  theme(legend.position = "bottom",panel.border=element_rect(linewidth=2),
                                plot.tag = element_text(face = 'bold'))

ggsave("C:/Users/Ictinike/Documents/Labs/GoldbergLab/Papers/figures/260720_SuppFigure_Cross_validation.pdf",p1,
       dpi=600,width=5,height=5,units="in")
```